# Generated by Django 4.1.3 on 2022-11-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captions', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
